# Machine Learning Zoomcamp

## 1.7 Introduction to Numpy

In [1]:
import numpy as np

## Creating arrays

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a = np.array([1,2,3,4,5,7,12])
a

array([ 1,  2,  3,  4,  5,  7, 12])

In [12]:
a[2] = 10
a

array([ 1,  2, 10,  4,  5,  7, 12])

In [14]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [20]:
# creates an array fill with numbers between the first parameter and the second parameter
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dementional arrays

In [22]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [28]:
n[0,1] = 20

In [30]:
n[0]

array([ 1, 20,  3])

In [32]:
n[2] = [1, 1, 1]

In [35]:
n[:, 2] = [0,1,2] 
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

## Randomly generated arrays

In [44]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [46]:
np.random.seed(2)
np.random.randint(low=0,high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations

In [57]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [60]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [61]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

## Comparison operations

In [62]:
a

array([0, 1, 2, 3, 4])

In [64]:
a >= 2

array([False, False,  True,  True,  True])

In [66]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [68]:
a > b

array([False, False,  True,  True,  True])

In [69]:
# only keeps the position values that returns True
a[a > b]

array([2, 3, 4])

## Summarizing operations

In [71]:
a

array([0, 1, 2, 3, 4])

In [73]:
a.min()

0

In [75]:
a.sum()

10

In [76]:
a.mean()

2.0