In [16]:
import numpy as np

u = np.array([2,4,5,6])
v = np.array([1,0,0,2])

## Multiplication
### Vector-vector multiplication (dot product)

In [17]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]

    return result

vector_vector_multiplication(u,v)

14.0

In [18]:
# numpy easy way
u.dot(v)

14

### Matrix-vector multiplication

In [19]:
u = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])

In [22]:
def matrix_vector_multiplication(u,v):
    assert u.shape[1] == v.shape[0]

    num_rows = u.shape[0]
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(u[i],v)

    return result

In [24]:
matrix_vector_multiplication(u,v)

array([14.,  5.,  5.])

In [25]:
u.dot(v)

array([14,  5,  5])

### Matrix-Matrix multiplication

In [26]:
v = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0]
])

In [27]:
def matrix_matrix_multiplication(u,v):
    assert u.shape[1] == v.shape[0]

    num_rows = u.shape[0]
    num_columns = v.shape[1]
    result = np.zeros((num_rows, num_columns))

    for i in range(num_columns):
        vi = v[:,i]
        uvi = matrix_vector_multiplication(u, vi)
        result[:, i] = uvi

    return result 
    

In [28]:
matrix_matrix_multiplication(u,v)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [29]:
u.dot(v)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity matrix

In [35]:
i = np.eye(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
v.dot(i)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Inverse

In [42]:
## only square matrix has inverse, meaning that only matrix with the same number of columns and rows are aviable to be inverse
vs = v[[0,1,2]]
vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [45]:
vs_inv = np.linalg.inv(vs)
vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [46]:
vs_inv.dot(vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])